routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/*
Route::get('/types/{type}', 'TypeController@show')->name('types.show');
 */
Route::group(['prefix' => 'types', 'as' => 'types.'], function () {
 //   Route::get('/', 'TypeController@index')->name('index');
    Route::get('/{name}', 'TypeController@show')->name('show');
});

Route::group(['prefix' => 'origins', 'as' => 'origins.'], function () {
 //   Route::get('/', 'OriginController@index')->name('index');
    Route::get('/{name}', 'OriginController@show')->name('show');
});

Route::group(['prefix' => 'champions', 'as' => 'champions.'], function () {
    Route::get('/', 'ChampionController@index')->name('index');
    Route::get('/{name}', 'ChampionController@show')->name('show');
});

app/Champion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Champion extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     *
     * @var array
     */
    protected $guarded = [];

    public function origins()
    {
        return $this->belongsToMany(Origin::class);
    }

    public function types()
    {
        return $this->belongsToMany(Type::class);
    }

    public function stats()
    {
        return $this->belongsToOne(Stat::class);
    }
}

app/Origin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Origin extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     *
     * @var array
     */
    protected $guarded = [];

    public function champions()
    {
        return $this->belongsToMany(Champion::class);
    }

}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     *
     * @var array
     */
    protected $guarded = [];

    public function champions()
    {
        return $this->belongsToMany(Champion::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ChampionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Champion;
use App\Stat;
use App\Type;
use App\Origin;


class ChampionController extends Controller

{
    /**
     * Create a new controller instance.
     *
     * @return void
     */


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $sortBy = request('sort_by');
        $sortDir = request('sort_dir');
       // $sortPage = request('sort_page');

        if ($sortBy) {
            $champions = Champion::orderBy($sortBy, $sortDir ?? 'asc')->paginate(20);
        } else {
            $champions = Champion::paginate(20);
        }

        return view('/champions/index', compact('champions'));
    }

    public function show($name)
    {
      //  $type = Type::where('name', $name)->with('champions')->first();

        $champion = Champion::where('name', $name)->first();

        return view('champions.show', compact('champion'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OriginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Origin;
use App\Type;

class OriginController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     *//*
    public function index()
    {
        return view('/origins/index');
    }*/

    public function show($name)
    {
        $origin = Origin::where('name', $name)->with('champions')->first();
        return view('origins.show', compact('origin'));
    }


}

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Type;
use App\Origin;

class TypeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    /*
    public function index()
    {
        return view('/types/index');
    }
     */



    public function show($name)
    {
        $type = Type::where('name', $name)->with('champions')->first();
        return view('types.show', compact('type'));
    }


}

resources/views/champions/index.blade.php
@extends('layouts.app') 
@section('content')
<div class="homepage">
    <div class="content">
        <div class="container emp-profile">
            <div class="col-sm-12 ">
                <div class="card">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 ">
                            <div class="card-body">
                                <div class="title m-b-md">

                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover table-condensed">
                                        <th>Avatar </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'Name', 'sort_dir' => handleSorting()])}}">Champion</a>
                                        </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'Health', 'sort_dir' => handleSorting()])}}">Health</a>
                                        </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'Armor', 'sort_dir' => handleSorting()])}}">Armor</a>
                                        </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'Mr', 'sort_dir' => handleSorting()])}}">Mag Resist</a>
                                        </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'DPS', 'sort_dir' => handleSorting()])}}">DPS</a>
                                        </th>
                                        <th>
                                            <a href="{{route('champions.index', ['sort_by' => 'Price', 'sort_dir' => handleSorting()])}}">Value</a>
                                        </th>

                                        @foreach ($champions as $champion)
                                        <tr class="noBorder">

                                            <td>
                                                <a href="{{ route('champions.show', ['champion' => $champion->name]) }}">
                                                    <img src="/img/lol_avatars/{{ $champion->avatar }}"
                                                        style="width:60px; height:60px">
                                                </a>
                                            </td>

                                            <td>{{ $champion->name}}</td>
                                            <td>{{ $champion->health}}</td>
                                            <td>{{ $champion->armor}}</td>
                                            <td>{{ $champion->mr}}</td>
                                            <td>{{ $champion->dps}}</td>
                                            <td>{{ $champion->price}} <i class="fas fa-coins"></i></td>
                                        </tr>
                                        @endforeach
                                    </table>
                                    {{-- {{ $champions->links() }} --}} {{ $champions->appends(request()->except('page'))->render() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection

resources/views/champions/show.blade.php
@extends('layouts.app') 
@section('content') @if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="container emp-profile-small">
    <form method="post">
        <div class="row">
            <div class="col-md-3">
                <div class="profile-img">
                    <img src="/img/lol_avatars/{{ $champion->avatar }}" style="width:160px; height:160px">


                </div>
            </div>

            <div class="col-md-7">



                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Ultimate</a>
                    </li>
                </ul>

            </div>
            <div class="col-md-2">

                <a href="{{ route('champions.index') }}" class="profile-edit-btn" style="margin-right: 8px;">Back</a>

            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="profile-work">
                    <h1>{{$champion->name}}</h1>


                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Health</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$champion->health}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Armor</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$champion->armor}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Mag resist</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$champion->mr}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Value</label>
                            </div>

                            <div class="col-md-6">
                                <p>{{$champion->price}} <i class="fas fa-coins"></i></p>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6">
                                <label>DPS</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$champion->dps}}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Class</label>
                            </div>
                            <div class="col-md-6">
                                @foreach ($champion->types as $type)
                                <p>
                                    <a href="{{ route('types.show', ['type' => $type->name]) }}">{{$type->name}}
                                    </a>
                                </p>
                                @endforeach
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Origin</label>
                            </div>
                            <div class="col-md-6">
                                @foreach ($champion->origins as $origin)
                                <p>
                                    <a href="{{ route('origins.show', ['origin' => $origin->name]) }}">{{$origin->name}}
                                    </a>
                                </p> @endforeach
                            </div>
                        </div>





                    </div>


                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

                        <div class="row">
                            <div class="col-md-9">
                                <p>{{$champion->description}}</p>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </form>
    <br>
    <hr>

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'GymApp') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>

    <div id="app">
        <nav class="navbar  navbar-light navbar-laravel navbar-left">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('Home', 'Home') }}
                </a> @php $types = \App\Type::all(); $origins = \App\Origin::all();
                @endphp

                <div class="dropdown">
                    <a href="{{route('champions.index')}}" class="navbar-brand" style="color:white">Champions</a>

                </div>

                <div class=" dropdown ">
                    <a class="navbar-brand " style="color:white ">Classes</a>
                    <div class="dropdown-content ">
                        @foreach ($types as $type)
                        <a href="{{ route( 'types.show', [ 'type'=> $type->name]) }}">{{$type->name}}</a> @endforeach
                    </div>
                </div>


                <div class="dropdown">
                    <a class="navbar-brand" style="color:white">Origins</a>
                    <div class="dropdown-content">
                        @foreach ($origins as $origin)
                        <a href="{{ route('origins.show', ['type' => $origin->name]) }}">{{$origin->name}}</a>
                        @endforeach
                    </div>
                </div>

                <div class="dropdown">
                    <a class="navbar-brand" style="color:white">Team Builder</a>
                </div>

                @auth
                <div class="dropdown">
                    <a class="navbar-brand" style="color:white">Profile</a>
                    <div class="dropdown-content">

                        <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Wyloguj') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </div>
                @endauth @guest

                <div class="dropdown">
                    <a class="navbar-brand" style="color:white">Login</a>
                    <div class="dropdown-content">
                        <a href="{{ route('login') }}">{{ __('Login') }}</a>
                        <a href="{{ route('register') }}">{{ __('Register') }}</a>
                    </div>
                </div>

                @endguest
            </div>
        </nav>

        <div class="container-fluid">
            <div id="elo"></div>
            @yield('content')
        </div>
    </div>

</body>

</html>

resources/views/layouts/error.blade.php
@if ($errors->has($what))
    <span class="invalid-feedback"><strong>{{ $errors->first($what) }}</strong></span>
@endif

resources/views/layouts/flash.blade.php
@foreach([
    'success' => 'success', 'confirmation-success' => 'success',
    'status' => 'info',
    'error' => 'danger', 'confirmation-danger' => 'danger'] as $type => $class)
    @if( Session::has( $type ) )
        <div id="alert" class="alert alert-{{$class}} alert-dismissible fade show" role="alert">
            <span class="alert-text mr-2">{!! Session::get( $type ) !!}</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
        </div>
    @endif
@endforeach

resources/views/layouts/footer.blade.php
<hr> Aplikacja tworzona, aby w godny sposób tworzyć zespoły w Teamfight Tactics!
<hr>

resources/views/origins/show.blade.php
@extends('layouts.app') 
@section('content')
<div class="homepage">


    <div class="content">

        <div class="container emp-profile">
            <div class="col-sm-12 ">
                <div class="card">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 ">

                            <div class="card-body">
                                <div class="title m-b-md">
                                    {{$origin->description}}
                                </div>



                                <div class="table-responsive" style="text-align:center;">
                                    <table class="table table-striped table-bordered table-hover table-condensed">

                                        <th>Avatar</th>

                                        <th>Champion</th>
                                        <th>Description</th>
                                        <th>Value</th>
                                       
                                        @foreach($origin->champions as $champion)
                                        <tr class="noBorder">
                                            <td>

                                                <a href="{{ route('champions.show', ['champion' => $champion->name]) }}">
                                             <img src="/img/lol_avatars/{{ $champion->avatar }}" style="width:60px; height:60px"></td>
                                        </a>
                                                <td>{{ $champion->name}}</td>
                                                <td class="description">{{ $champion->description}}</td>
                                                <td>{{ $champion->price}} <i class="fas fa-coins"></i></td>





                                        </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection

resources/views/types/show.blade.php
@extends('layouts.app') 
@section('content')
<div class="homepage">
    <div class="content">
        <div class="container emp-profile">
            <div class="col-sm-12 ">
                <div class="card">
                    <div class="row justify-content-center">
                        <div class="col-sm-10 ">
                            <div class="card-body">
                                <div class="title m-b-md">
                                    {{$type->description}}
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover table-condensed">
                                        <th>Avatar </th>
                                        <th>Champion</th>
                                        <th>Description</th>
                                        <th>Value</th>

                                        @foreach($type->champions as $champion)
                                        <tr class="noBorder">

                                            <td>
                                                <a href="{{ route('champions.show', ['champion' => $champion->name]) }}">
                                                <img src="/img/lol_avatars/{{ $champion->avatar }}" style="width:60px; height:60px">
                                            </a>
                                            </td>

                                            <td>{{ $champion->name}}</td>
                                            <td class="description">{{ $champion->description}}</td>
                                            <td>{{ $champion->price}} <i class="fas fa-coins"></i></td>
                                        </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection